# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.version.version

'1.19.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [ ]:
np.ones(10).nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null_vector=np.zeros(10)
null_vector[5]=1
null_vector

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
_10_to_49=np.arange(start=10, stop=49)
_10_to_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
#I used same array with previous question
np.flip(_10_to_49)

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
_3x3_matrix=np.arange(0, 9).reshape(3,3)
_3x3_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [ ]:
non_zero=np.array([1,2,0,0,4,0])
non_zero[non_zero!=0]
    

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
random_3x3x3=np.random.randint(0,10,(3,3,3))
random_3x3x3

array([[[3, 1, 3],
        [5, 7, 1],
        [0, 5, 5]],

       [[4, 1, 1],
        [4, 1, 1],
        [3, 5, 2]],

       [[4, 4, 1],
        [3, 5, 0],
        [4, 9, 3]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
x=np.random.normal(size=(10, 10)) #I choosed use normalized values
print(x.max())
print(x.min())

2.4933805759469685
-2.4196157899063544


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
_30_vector=np.random.randint(0,10,(1,30))
np.average(_30_vector)

4.466666666666667

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
y=np.array(([1,0,1],[1,0,1]))
y

array([[1, 0, 1],
       [1, 0, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
existing_array=np.ones((4,4))
np.pad(existing_array,(1,1))


array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan #equal to nan
np.nan == np.nan #equal to false because nan values can't be in comparison
np.inf > np.nan #equal to false because nan values can't be in comparison
np.nan - np.nan #eqaul nan but I don't know the reason maybe same with 0-0 or 0+0
np.nan in set([np.nan]) #true 
0.3 == 3 * 0.1 #false float values can't be absolute value

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
np.diagflat([1,2,3,4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
dots=np.ones((8, 8))
dots[::2,1::2] = 0
dots[1::2,::2] = 0
dots

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
one_zero=np.array([1,0])
np.tile(one_zero,(8,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
np.random.normal(size=(10, 10))

array([[ 1.11111145, -1.09865303, -0.56296457,  0.66818802, -1.01792234,
        -0.24358295,  0.5657586 , -0.36910122, -0.41795104, -0.80292846],
       [-1.10305906, -1.36992337, -0.82761173, -1.10117926,  0.53653631,
        -0.45597035, -1.83428185, -0.60406162,  2.43279075,  0.41918599],
       [ 1.66091102, -1.37086645,  0.92579094, -0.41736851, -1.34372052,
         0.75869296, -0.89621172,  0.15161522, -0.21514811, -1.5326065 ],
       [ 1.05126911,  0.21824582, -2.31394335, -0.31805865, -0.62167796,
        -2.48835439,  0.72306587, -1.11536047, -0.85962322,  0.58927261],
       [ 0.15383496,  0.83212912, -0.62832083,  0.06016857, -1.17436965,
         1.2155129 , -0.28510215, -0.0306816 ,  1.59493177,  1.02918191],
       [-1.21230883,  1.96383576,  0.53897163,  0.92040395,  0.40465695,
        -0.47003441, -0.08035854, -0.91630214,  0.3672834 ,  0.80100008],
       [-0.90657596,  1.30281157, -0.83738299,  1.44427096,  0.82815349,
         1.19644334, -0.18010323,  1.0630546 

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
RGBA = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
RGBA

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

just note for myself

**Why ubyte??**
![why ubyte?](https://i.ibb.co/bRS59Qd/sil.jpg)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
X=np.random.randint(0,10,(5,3))
Y=np.random.randint(0,10,(3,2))
np.dot(X,Y)

array([[ 6, 91],
       [20, 67],
       [24, 64],
       [14, 74],
       [ 6, 99]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
negate=np.arange(9)
np.multiply(negate[4:8],-1)

array([-4, -5, -6, -7])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) 
#yep it is changing because sum function of numpy it includes ??? I don't know :)

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(10)
Z**Z
2<<Z>>2
Z<-Z
1j*Z
Z/1/1
Z<Z>Z #only this one isn't legal

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
#I SHOULD TURN BACK BECAUSE I COULDN'T  UNDERSTAND

zero_float=np.arange(-10,10,0.1)
np.round(zero_float,0)

array([1., 1., 1., 0., 0., 1., 0., 0., 0., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
X=np.random.randint(0,10,(3,3))
Y=np.random.randint(0,10,(3,3))
np.intersect1d(X, Y)

array([3, 4, 5, 6, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all='ignore')
np.seterr(all='ignore')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

It is false because emath helps us to find more scientific results 

In this case it finds complex numbers (1+j or j)

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
today = np.datetime64('today', 'D')
yesterday=np.datetime64('today','D')- np.timedelta64(1, 'D') 
tomorrow=np.datetime64('today','D')+ np.timedelta64(1, 'D') 
print(f' today: {today} \n yesterday: {yesterday} \n tomorrow: {tomorrow}')

 today: 2021-03-22 
 yesterday: 2021-03-21 
 tomorrow: 2021-03-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
date=np.arange('2016-06-01', '2016-06-30', dtype='datetime64[D]')
date

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=np.random.randint(0,10,(3,3,3))
B=np.random.randint(0,10,(3,3,3))
C=np.random.randint(0,10,(3,3,3))
np.multiply(np.add(A,B),np.divide(np.negative(A),2))

array([[[-81. , -45. ,  -4. ],
        [-52. ,  -1. , -64. ],
        [-22. , -26. ,  -4. ]],

       [[-30. , -27.5, -25. ],
        [-67.5,  -2.5, -16.5],
        [ -0.5, -68. ,   0. ]],

       [[-15. , -22. , -49.5],
        [-45. , -11. , -31.5],
        [-45. ,   0. , -52.5]]])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [ ]:
random_array=np.random.uniform(low=-5.5, high=9.3, size=(5,3))
#first method
print(np.floor(random_array))
#second method
print(np.ceil(random_array))
#third method
print(random_array.astype(int))
#fourth method
print(np.trunc(random_array))
#fifth method 
random_array%random_array # :))

[[ 8.  4.  6.]
 [-2.  1. -2.]
 [-5. -1.  4.]
 [ 9.  1. -4.]
 [ 1.  8.  0.]]
[[ 9.  5.  7.]
 [-1.  2. -1.]
 [-4. -0.  5.]
 [10.  2. -3.]
 [ 2.  9.  1.]]
[[ 8  4  6]
 [-1  1 -1]
 [-4  0  4]
 [ 9  1 -3]
 [ 1  8  0]]
[[ 8.  4.  6.]
 [-1.  1. -1.]
 [-4. -0.  4.]
 [ 9.  1. -3.]
 [ 1.  8.  0.]]


array([[ 0.,  0.,  0.],
       [-0.,  0., -0.],
       [-0., -0.,  0.],
       [ 0.,  0., -0.],
       [ 0.,  0.,  0.]])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.random.uniform(low=0, high=4, size=(5,5))

array([[1.15527644, 3.12934846, 0.87769468, 1.11354696, 3.73820191],
       [3.57924164, 0.95805118, 2.3265639 , 3.66232503, 2.7877604 ],
       [1.62400664, 2.95959286, 3.71538175, 1.10890177, 3.16860034],
       [2.34053479, 1.81602498, 1.48349357, 2.11225398, 1.47611027],
       [0.74860815, 1.67236321, 0.85077269, 2.77550227, 3.515912  ]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import random
def generating_38(n):
    generate_list=[]
    for i in range(n):
        generate_list.append(random.randint(0,n))
    np.array(generate_list)
    return generate_list

generating_38(10)
def iterable(n):
    iterable = (x*x for x in range(10))
    np.fromiter(iterable, float)

iterable(10)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
x=np.random.uniform(low=0, high=10, size=(10,))
np.random.choice(np.setdiff1d(range(1,10), x))


4

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [7]:
x=np.random.uniform(low=0,high=10,size=(10))
np.sort(x)

array([4.2362839 , 5.08026789, 5.24725604, 6.86252472, 7.86536187,
       8.15631363, 8.51026272, 8.58806876, 9.00747181, 9.37167855])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [8]:
A=np.random.normal([np.random.uniform(size=5)])
B=np.random.normal([np.random.uniform(size=5)])
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
X=np.array(([1,2,3],[4,5,6]))
X[[0,1]]=X[[1,0]]
X

array([[4, 5, 6],
       [1, 2, 3]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def computing_average(array):
    average_array=[]
    for i in range(len(array)):
        average_array.append(np.average(array[[i]]))
    return np.array(average_array)
array=np.array([[1,2,3],[2,4,6],[3,6,9]])

computing_average(array)

array([2., 4., 6.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=796ba814-f632-4502-b0d7-7e2f8f9e546d' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>