# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [1]:
import numpy as np
import pandas as pd

In [37]:
def add_vectors(u, v):
    """
      >>> add_vectors([1, 0], [1, 1])
      [2, 1]
      >>> add_vectors([1, 2], [1, 4])
      [2, 6]
      >>> add_vectors([1, 2, 1], [1, 4, 3])
      [2, 6, 4]
      >>> add_vectors([11, 0, -4, 5], [2, -4, 17, 0])
      [13, -4, 13, 5]
      >>> a = [1, 2, 3]
      >>> b = [1, 1, 1]
      >>> add_vectors(a, b)
      [2, 3, 4]
      >>> a
      [1, 2, 3]
      >>> b
      [1, 1, 1]
    """
    u=np.array(u)
    v=np.array(v)
    return u+v
a=[1,2,3]
b=[1,1,1]
add_vectors(a,b)

array([2, 3, 4])

Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [4]:
def scalar_mult(s, v):
    """
      >>> scalar_mult(5, [1, 2])
      [5, 10]
      >>> scalar_mult(3, [1, 0, -1])
      [3, 0, -3]
      >>> scalar_mult(7, [3, 0, 5, 11, 2])
      [21, 0, 35, 77, 14]
      >>> a = [1, 2, 3]
      >>> scalar_mult(4, a)
      [4, 8, 12]
      >>> a
      [1, 2, 3]
    """
    s=np.array(s)
    return s*v
scalar_mult(a,2)

array([2, 4, 6])

Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [6]:
x=[2, 0, -1, 1]
y=[1, 5, 2, 0]

def dot_product(u, v):
    """
      >>> dot_product([1, 1], [1, 1])
      2
      >>> dot_product([1, 2], [1, 4])
      9
      >>> dot_product([1, 2, 1], [1, 4, 3])
      12
      >>> dot_product([2, 0, -1, 1], [1, 5, 2, 0])
      0
    """
    u=np.array(u)
    v=np.array(v)
    return np.dot(u,v)

dot_product(x,y)

0

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [25]:
def copy_matrix(matrix):
    """
      >>> copy_matrix([[1, 2], [3, 4]])
      [[1, 2], [3, 4]]
      >>> copy_matrix([[1, 2, 3], [4, 5, 6]])
      [[1, 2, 3], [4, 5, 6]]
      >>> copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
      [[1, 2], [3, 4], [5, 6], [7, 8]]
      >>> m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> copyofm = copy_matrix(m)
      >>> copyofm
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> for row_num, row in enumerate(copyofm):
      ...     for col_num, col_val in enumerate(row):
      ...         copyofm[row_num][col_num] = 42
      ...
      >>> copyofm
      [[42, 42, 42], [42, 42, 42], [42, 42, 42]]
      >>> m
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
    """
    return np.array(matrix)
matrix1=[[1, 2], [3, 4]]
copy_matrix(matrix1)


array([[1, 2],
       [3, 4]])

In [32]:
def add_row(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_row(m)
      [[0, 0], [0, 0], [0, 0]]
      >>> n = [[3, 2, 5], [1, 4, 7]]
      >>> add_row(n)
      [[3, 2, 5], [1, 4, 7], [0, 0, 0]]
      >>> n
      [[3, 2, 5], [1, 4, 7]]
    """
    lis=[]
    for i in matrix:
        matrix_len=len(i)
    for j in range(matrix_len):
        lis.append(0)
    return np.vstack([matrix,lis])
add_row(matrix1)

array([[1, 2],
       [3, 4],
       [0, 0]])

In [34]:
def add_column(matrix):
    """
      >>> m = [[0, 0], [0, 0]]
      >>> add_column(m)
      [[0, 0, 0], [0, 0, 0]]
      >>> n = [[3, 2], [5, 1], [4, 7]]
      >>> add_column(n)
      [[3, 2, 0], [5, 1, 0], [4, 7, 0]]
      >>> n
      [[3, 2], [5, 1], [4, 7]]
    """
    lis=[]
    for i in matrix:
        matrix_len=len(i)
    for j in range(matrix_len):
        lis.append(0)
    return np.column_stack([matrix,lis])

add_column(matrix1)

array([[1, 2, 0],
       [3, 4, 0]])

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [60]:
def add_matrices(c,d):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> b = [[2, 2], [2, 2]]
      >>> add_matrices(a, b)
      [[3, 4], [5, 6]]
      >>> c = [[8, 2], [3, 4], [5, 7]]
      >>> d = [[3, 2], [9, 2], [10, 12]]
      >>> add_matrices(c, d)
      [[11, 4], [12, 6], [15, 19]]
      >>> c
      [[8, 2], [3, 4], [5, 7]]
      >>> d
      [[3, 2], [9, 2], [10, 12]]
   """
    c=np.array(c)
    d=np.array(d)
    return c+d
c=[[8, 2], [3, 4], [5, 7]]
d=[[3, 2], [9, 2], [10, 12]]

add_matrices(c,d)

array([[11,  4],
       [12,  6],
       [15, 19]])

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [62]:
def scalar_mult(s, m):
    """
      >>> a = [[1, 2], [3, 4]]
      >>> scalar_mult(3, a)
      [[3, 6], [9, 12]]
      >>> b = [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
      >>> scalar_mult(10, b)
      [[30, 50, 70], [10, 10, 10], [0, 20, 0], [20, 20, 30]]
      >>> b
      [[3, 5, 7], [1, 1, 1], [0, 2, 0], [2, 2, 3]]
    """
    s=np.array(s)
    m=int(m)
    return np.dot(s,m)
scalar_mult(c,2)

array([[16,  4],
       [ 6,  8],
       [10, 14]])

Write functions row_times_column and matrix_mult:

In [64]:
def row_times_column(m1, row, m2, column):
    """
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
      19
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
      22
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
      43
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
      50
    """
    m1=np.array(m1)
    m2=np.array(m2)
    return np.matmul(m1,m2)[row][column]
a=[[1, 2], [3, 4]]
b=[[5, 6], [7, 8]]
row_times_column(a,0,b,0)


19

In [65]:
def matrix_mult(m1, m2):
   """
      >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      [[19, 22], [43, 50]]
      >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      [[31, 19], [85, 55]]
      >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      [[39, 54, 69], [13, 23, 33], [14, 19, 24]]
    """
   m1=np.array(m1)
   m2=np.array(m2)
   return np.matmul(m1,m2)

matrix_mult(a,b)

array([[19, 22],
       [43, 50]])

Write a function transpose that takes a matrix as an argument and returns is transpose:

In [75]:
def transpose(m):

  return np.transpose(m)

a=[[1, 2], [3, 4]]
transpose(a)

array([[1, 3],
       [2, 4]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=796ba814-f632-4502-b0d7-7e2f8f9e546d' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>