In [ ]:
import numpy as np

## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [ ]:
# okay numpy is great but... how would you inverse a matrix by hand?
A=np.array([[3,1,2], [-5,4,1], [0,3,-8]])
B=np.array([[0,5,-1],[3,2,-1],[10,0.5,4]])



def inverse_matrix(A):
    return np.linalg.inv(A)

print(inverse_matrix(A))
print(np.linalg.inv(B))

[[ 0.2        -0.08        0.04      ]
 [ 0.22857143  0.13714286  0.07428571]
 [ 0.08571429  0.05142857 -0.09714286]]
[[-0.09289617  0.22404372  0.03278689]
 [ 0.24043716 -0.10928962  0.03278689]
 [ 0.20218579 -0.54644809  0.16393443]]


![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [ ]:
# Just answer using code --> easy stuff!
A = np.array([[3, 0.6, 4, -3],[-1.3,4,0,8.6],[7,0,-8,0.006]])
B = np.array([[3, -5.76, 45, 0],[2, -2, 1.3 , 9],[-9, 0,0,0]])
C = np.array([[0,1009, -66.7849, 90],[0,5,4,-0.07],[-7.7,0,0,0]])
D = A + B - C
# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 
print(D[1][2])
print(D[2][0])

-2.7
5.7


![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [ ]:
A = np.array([0.6,-15,2,5,98])
B = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])
C=np.dot(A.T,B)
print(C)
print(C[2])

[-102.8  255.2  595.6]
595.6


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=796ba814-f632-4502-b0d7-7e2f8f9e546d' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>