In [2]:
import numpy as np

**72. How to swap two rows of an array?** 

In [46]:
X=np.array(([1,2,3],[4,5,6]))
X

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
X[[0,1]]=X[[1,0]]
X


array([[4, 5, 6],
       [1, 2, 3]])

**75. How to compute averages using a sliding window over an array?**

array([[1, 4, 3],
       [4, 5, 6]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=79673256-d468-4dc3-bcd4-af2c4cf3525d' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>